### ISSUE TITLE
Separate playlist window

### ISSUE THREAD

**Issue by schriftgestalt** [pdherbemont/Glasses#25]
Is it possible to have a single window for the playlist? (accessible through a style)

**Comment by pdherbemont** [comment]
I think this will end up being a mess, especially since we support opening multiple document.

The current from of the playlist is bound to change.

Mac OS is giving its user a hard time enough at window management, so I think this is something I won't fix.

That said, we could probably expose it via a style, but the code is not here. I guess the amount of work to maintain it would be too hard.

(You have the debug playlist if you are really obsessed by it however :) ...)
Are those explanations satisfying for you?

**Comment by CarterA** [comment]
I'd say don't implement this. Ever. It's one of the bad parts of the old VLC. I ran this by several designers and everyone agrees that it should be a single window, no matter what. And I think that adding code to allow it via a style just adds extra bloat and unnecessary code to the app.

**Comment by pdherbemont** [comment]
Closing. Feel free to come up with an opt-in patch if you really want to have this. :-)
