### ISSUE TITLE
More Thoughts on the Interface

### ISSUE THREAD

**Issue by schriftgestalt** [pdherbemont/Glasses#27]
I thought about this a bit and I think I found what bothered me.

But first some questions. 

How do you see the main purpose of the Slash Screen? Just as a fast jump in to the program?

How do you use the Playlist? Just now it is the only way to access files from My Videos. It always starts the first one which is not what I want, when I click on something called My Videos.

I see a problem with the structure and hierarchy:

There are two use scenarios:
- double click a movie in the finder. You expect a simple video window like QuickTime or QuickLook (Without any splash screen or playlist).
- You open VLC and want to browse/discover with the splash screen.

The browsing should lead to one or more files you select to watch. 

So you should be presented with a tree of choices.

This could be like Front Row or iTunes (the structure of the navigation, not the interface) . You get some options (like Unfinished, my Video, Shoutcast Radio, TV...) If you select on, you get the details in another column. 

Structural, the unfinished list and the playlist are the same (they are a list of videos chosen from some criteria) and should be treated the same.

In the selection process, the actual video is the leave in the tree. The general visualization of a selection tree is from top left to bottom right. So the present solution with the playlist on the right side breaks this flow. 

Do you really need to see the playlist on the video window. In window mode you most likely have a finder window just behind and it does a much better job on presenting file. In fullscreen mode you either want to see the video OR the playlist/media selection. So I would prefer a more Front Row like behavior of switching screens.

So my point is to have a video window and a media browser. Both have a clear purpose. The slash screen could be much more useful as a media browser and the playlist as it is now would only be used if you open and play more than one file at once. 

This is still not as clear and structures as I would like it. Maybe a discussion can tighten it up.

Georg

**Comment by pdherbemont** [comment]
Hey Georg,

This is something quite difficult and a discussion is important.

So, I am not against a master detail view for the splash screen. It actually makes sense, and from the different feedback I had, this is pretty much something no one likes.

About playlist:
- I do use overlay playlist in fullscreen, and I do also use it in window mode. (Especially with the Freebox and soon to be EyeTV).
- I don't use the "My Video" thing.
- Playlist can be useful when you have a multiple part movie.

About Unfinished Movies (Or the Movie Stack):
- This is a special "Library" items, and if we build a master detail interface it has to appear contextually.

About Master Detail:
- The detail content would be ok for the other SD, yet, we should probably make sure one can open a specific SD, with the overlay playlist. (I do like that.). An other option would be to do like we currently do, but make sure we actually play the selected Media.

So, end words, it definitely makes sense to use one. I'd like to know what's the status of Carter work, carter?

Pierre.

**Comment by schriftgestalt** [comment]
I now understand your usage of the playlist and my problem with it. On the splash screen I only used the "my Video" section (to watch the movies in my movies folder) and in this case, it is very inconvenient, if it opens the video window. If there could be another step in between I would be happy. 

Also I don’t like to see alle the recent (at least the unfinished ones) movies on the splash screen. Sometimes you open vlc in front of other people and you don’t like them to know about your preference on soup operas (or ...).

And what are SDs?

**Comment by pdherbemont** [comment]
Oh, right :) SD are VLC "services discovery". A seldom known feature of VLC. For instance, if you try to share a file, you should automatically see VLC's SAP announcement SD moving in the Library view. Same if you have a Freebox (TV set top box), or UPnP content.

Currently the only nice use case of "My Video", is to be able to browse local media in fullscreen. But that's rather a hack, I concede. I think that for the first version, this may stay that way. Next version could enhance fullscreen a bit more.

For recent items, it is something I would like to see right when I open VLC, because that's what fit best in my use case. I believe this is also a nice way to use VLC, and we must make sure that this is very discoverable. We could (and probably should) have an option not to remember anything and stuff. (VLC is being used for porn. Right :-) And then for privacy it makes sense. But this has to be an option.)

The next step is to bring the full list of unwatched movies (by watching a folder), and then the list of watched movies (less useful I guess). It would nicely help people downloading their movies and stuff.

Pierre.

**Comment by pdherbemont** [comment]
Closing for now.
