### ISSUE TITLE
Video distortion on fast movements

### ISSUE THREAD

**Issue by fkuehne** [pdherbemont/Glasses#5]
Since very recently, Lunettes shows lots of image distortions in the video after cuts and faster movements. These are demonstrated here:

[http://jones.videolan.org/~videolan/fpk/distortion1.jpg]
[http://jones.videolan.org/~videolan/fpk/distortion2.jpg]

This happens with both interlaced and non-interlaced contents.

**Comment by pdherbemont** [comment]
I have a fix for that. This is due to recent OpenGL rework in vlccore. Fenrir won't accept it though, for some obscure reason on my side. He said he'll have a look at the VDD.

**Comment by pdherbemont** [comment]
Here is my diff
diff --git a/modules/video_output/opengl.c b/modules/video_output/opengl.c
index 016ec8e..0b3576d 100644
--- a/modules/video_output/opengl.c
+++ b/modules/video_output/opengl.c
@@ -374,17 +374,40 @@ static void Render( vout_thread_t *p_vout, picture_t *p_pic )
 {
     vout_sys_t *p_sys = p_vout->p_sys;
-    picture_t *p_next = p_sys->p_current;
  +
-    if( VLCGL_TEXTURE_COUNT > 1 )
-    {
-        /\* Get the next picture to display */
-        p_next = picture_pool_Get( p_sys->p_pool );
-        assert( p_next );
-    }
-  if( p_sys->p_current )
   {
       assert( p_sys->p_current->p[0].p_pixels == p_pic->p[0].p_pixels );
- ```
     /* Make sure we have the prepare after the picture_pool_Get,
  ```
-         \* because picture_pool_Get() will bind the new picture texture,
-         \* and vout_display_opengl_Prepare() bind the current rendered picture
-         \* texture.
-         \* DisplayVideo() will effectively use the last binded texture. */
  +
       vout_display_opengl_Prepare( &p_sys->vgl, p_sys->p_current );
- ```
     picture_Release( p_sys->p_current );
  ```
  
   }
-    p_sys->p_current = picture_pool_Get( p_sys->p_pool );
-    if( p_sys->p_current )
-    if( p_sys->p_current != p_next ) {
-        if( p_sys->p_current )
-            picture_Release( p_sys->p_current );
-   
-        /\* Swap the picture texture on opengl vout side. */
-        p_sys->p_current = p_next;
  +
-        /\* Now, switch the only picture that is being used
-         \* to render in the backend to point to our "next"
-         \* picture texture */
       p_pic->p[0].p_pixels = p_sys->p_current->p[0].p_pixels;
-    }
  
   VLC_UNUSED( p_pic );
  }

**Comment by pdherbemont** [comment]
Closing as this belongs to vlc.
