### ISSUE TITLE
Can't upgrade to 1.0 beta 6 (2010-04-30)

### ISSUE THREAD

**Issue by SteveBell** [pdherbemont/Glasses#70]
When I check for updates from within Lunettes all I get is an error:
"Update Error! An error occurred in retrievin update information. Please try again later."

Now I can't get the latest beta. Can this be fixed?

I hope this is the right place for this issue (I'm a total noob on github, so don't bash me).

**Comment by ghost** [comment]
This one is the latest: http://github.com/downloads/pdherbemont/Glasses/Lunettes-5.0.zip

**Comment by SteveBell** [comment]
ok, then am I mistaking, that there is a 6.0 hanging around on the download page?

**Comment by ghost** [comment]
There is, but it has an older upload date. I just went by the upload date, rather than the number. I suspect "Lunettes 1.0 Beta - test5" is just incorrectly named as it seems to be the most recent upload.

BTW, I've made my own build from the latest source code snapshot. If you want to try it out I've uploaded it here: http://forboden.com/coding/Lunettes.app.zip

**Comment by SteveBell** [comment]
ok, thanks for clearing things up a bit. Sorry, I don't have the time to really check out your fork. what's the point of it? why not contribute to the glasses build?

**Comment by ghost** [comment]
It's not a fork. I've taken the latest snapshot of the source code and compiled it.
